[package]
name = "log-parser-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "2.0.3", features = ["postgres"] }
dotenv = "0.15.0"
indicatif = "0.17.3"
rand = "0.8.5"
